"use client"
import { Rajdhani } from 'next/font/google';
/* import localFont from "next/font/local"; */
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";
import StoreProvider from "@/store/provider";

/* const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
 */
/* const kanit = Kanit({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-kanit',
}); */

const rajdhani = Rajdhani({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-rajdhani',
});

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${rajdhani.variable} antialiased`}
      >
        <StoreProvider>
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
